# Generated by Django 2.2.17 on 2021-04-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('age', models.PositiveSmallIntegerField(default=0)),
                ('first_name', models.CharField(default='Введите имя пользователя', max_length=30, verbose_name='first_name')),
                ('last_name', models.CharField(default='Введите фамилию пользователя', max_length=150, verbose_name='last_name')),
                ('username', models.CharField(max_length=64, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
